"""add lvye_account.

Revision ID: 3bf0c51dfcf1
Revises: 4eadc089674e
Create Date: 2016-01-26 01:19:05.469429

"""

# revision identifiers, used by Alembic.
revision = '3bf0c51dfcf1'
down_revision = '4eadc089674e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lvye_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=32), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lvye_account')
    ### end Alembic commands ###
