"""add created_on to verification_code.

Revision ID: 59645a8811d3
Revises: None
Create Date: 2015-08-31 15:55:16.564146

"""

# revision identifiers, used by Alembic.
revision = '59645a8811d3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_code', sa.Column('created_on', sa.DateTime(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_code', 'created_on')
    ### end Alembic commands ###
