"""add transaction type cheque.

Revision ID: 1a09d3c6f84d
Revises: 1fab4bdccfb3
Create Date: 2016-01-22 17:48:37.771675

"""

# revision identifiers, used by Alembic.
revision = '1a09d3c6f84d'
down_revision = '1fab4bdccfb3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cheque_record',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tx_id', sa.BigInteger(), nullable=False),
    sa.Column('sn', sa.CHAR(length=32), nullable=False),
    sa.Column('type', sa.Enum('INSTANT', 'LAZY'), nullable=False),
    sa.Column('signature', sa.CHAR(length=32), nullable=True),
    sa.Column('from_id', sa.Integer(), nullable=False),
    sa.Column('to_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('valid_minutes', sa.Integer(), nullable=False),
    sa.Column('client_notify_url', sa.VARCHAR(length=128), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tx_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cheque_record')
    ### end Alembic commands ###
