"""add info to cheque record.

Revision ID: 26372df9505f
Revises: 488e5030eb8c
Create Date: 2016-01-24 13:45:27.185291

"""

# revision identifiers, used by Alembic.
revision = '26372df9505f'
down_revision = '488e5030eb8c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cheque_record', sa.Column('info', sa.CHAR(length=128), nullable=True, info={'after': 'signature'}))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cheque_record', 'info')
    ### end Alembic commands ###
