"""add client callback/notify urls to prepaid record.

Revision ID: 3bf363900605
Revises: 412248e937cf
Create Date: 2015-09-01 15:46:36.384893

"""

# revision identifiers, used by Alembic.
revision = '3bf363900605'
down_revision = '412248e937cf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prepaid_record', sa.Column('client_callback_url', sa.VARCHAR(length=128), nullable=True))
    op.add_column('prepaid_record', sa.Column('client_notify_url', sa.VARCHAR(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prepaid_record', 'client_notify_url')
    op.drop_column('prepaid_record', 'client_callback_url')
    ### end Alembic commands ###
