# coding=utf-8
#商户编号
customernumber="10012438801"
#
#商户密钥
keyValue="574584H38Msx80980026QKzbX588Zv0xh95ph8ZG67dj7x69k5091xvm0013"
#
#分账账号注册请求地址
registerURL="https://o2o.yeepay.com/zgt-api/api/register"
#
#账户信息修改接口请求地址
updateAccountURL="https://o2o.yeepay.com/zgt-api/api/modifyRequest"
#
#账户信息修改接口请求地址
queryUpdateURL="https://o2o.yeepay.com/zgt-api/api/queryModifyRequest"
#
#交易请求地址
requestURL="https://o2o.yeepay.com/zgt-api/api/pay"
#
#订单查询请求地址
queryURL="https://o2o.yeepay.com/zgt-api/api/queryOrder"
#
#非交易转账请求地址
transferURL="https://o2o.yeepay.com/zgt-api/api/transfer"
#
#非交易转账查询请求地址
transferQueryURL="https://o2o.yeepay.com/zgt-api/api/transferQuery"
#
#订单转账请求地址
divideURL="https://o2o.yeepay.com/zgt-api/api/divide"
#
#订单转账查询请求地址
divideQueryURL="https://o2o.yeepay.com/zgt-api/api/queryDivide"
#
#订单退款请求地址
refundURL="https://o2o.yeepay.com/zgt-api/api/refund"
#
#订单退款查询请求地址
refundQueryURL="https://o2o.yeepay.com/zgt-api/api/queryRefund"
#
#担保确认请求地址
confirmURL="https://o2o.yeepay.com/zgt-api/api/settleConfirm"
#
#余额查询请求地址
balanceQueryURL="https://o2o.yeepay.com/zgt-api/api/queryBalance"
#
#提现接口请求地址
cashTransferURL="https://o2o.yeepay.com/zgt-api/api/cashTransfer"
#
#提现查询接口请求地址
queryCashTransferURL="https://o2o.yeepay.com/zgt-api/api/queryCashTransfer"
#
#结算结果查询接口请求地址
querySettlementURL="https://o2o.yeepay.com/zgt-api/api/querySettlement"


if __name__ == '__main__':
    pass